### PR TITLE
add Foldable and Traversable instances to IPRTable

### PR DESCRIPTION
**Pull request by greydot**
Maybe it is a good idea to drop the internal toList implementation in favor of the one from Data.Foldable?

### CODE REVIEW

**Comment by kazu-yamamoto** [comment]
Would you fix the test first?

**Comment by greydot** [comment]
Sorry for that. I should add Travis to my account perhaps.
Do we need to support GHC 7.4 builds?

**Comment by kazu-yamamoto** [comment]
My policy is to support three versions of GHC. GHC 7.10 has been released but Travis CI does not provide support for GHC 7.10. So, I would like to support GHC 7.4 at this moment.

What is a technical problem to support GHC 7.4 for this change?

**Comment by greydot** [comment]
The problem is that Data.Foldable in ghc 7.4 does not provide foldl' (strict foldl) function, which is used in fromList. So, there are several ways to fix this issue
A. Drop GHC 7.4 support and wait for 7.10 support in Travis (I hope it won't take long).
B. Import foldl' from Data.List. This has to be a qualified import, otherwise we get a name conflict with GHC >=7.6.
C. Use the lazy function which GHC 7.4 provides.

**Comment by kazu-yamamoto** [comment]
OK. Let's drop the support of GHC 7.4. Your pull request has been merged.

**Comment by kazu-yamamoto** [comment]
Version 1.4.0 has been released.

**Pull request merged**
