### PR TITLE
GHC 9.2 compatibility updates

### PR DESCRIPTION
**Pull request by vdukhovni**
Also replace long dead Travis CI with Github CI.

### CODE REVIEW

**Review by kazu-yamamoto — APPROVED** [review]
Tested with GHC 9.2.1. Worked fine. Thanks.

**Comment by kazu-yamamoto** [comment]
Merged. Thank you for your contribution!

**Comment by vdukhovni** [comment]
Thanks for merging.  Looks like we need to arrange to build hspec-discover for github CI to work. Can you take care of that, or is that in my court?

**Comment by vdukhovni** [comment]
Perhaps: https://github.com/vdukhovni/iproute/commit/b429d7888cfd05c49dd8c5c13e7329b682a89397
would do the trick?

**Comment by kazu-yamamoto** [comment]
This is your contribution. So, send a PR please.

**Pull request merged**
