### PR TITLE
Simplify Field Format (FF) switch

### PR DESCRIPTION
**Pull request by vdukhovni**
Now just a cascase of single-constructor cases, mostly in (intutive) expected
order of frequency.  Also, no benefit in unpacking the FF constructors.

### CODE REVIEW

**Comment by vdukhovni** [comment]
Sorry about springing one more commit on you, after you already merged #46, but I hope you will agree this is a reasonable simplification.  The removal of the `{-# UNPACK #-}` pragmas is optional, they make no measurable performance difference.

The change that's more material is the rewrite of `output32`, that makes it simpler IMHO, with no loss of performance.

**Comment by kazu-yamamoto** [comment]
Three-days holiday is about to begin in Japan. I will come back to this issue in the next week. Do you want one more new release after merging?

**Comment by vdukhovni** [comment]
> Three-days holiday is about to begin in Japan. I will come back to this issue in the next week. Do you want one more new release after merging?

Enjoy the spring equinox, and stay safe!

No new release is needed, since the change is cosmetic (code hygiene).  But if no other changes are likely unless a miracle happens, then it may be easier to release now, and not have to think about it again later.

**Comment by kazu-yamamoto** [comment]
Merged.

**Pull request merged**
