### PR TITLE
make toIPv6/fromIPv6 work with byte-lists

### PR DESCRIPTION
**Pull request by greydot**
Hey,

This change makes toIPv[46] and fromIPv[46] more consistent, and makes reading IPv6 addresses from raw bytestrings much easier. The downside is it breaks the API compatibility.

### CODE REVIEW

**Comment by kazu-yamamoto** [comment]
I would like to maintain backward compatibility while making the library bytestring friendly. So, let's discuss requirements first?

I'm sorry for this late response. I'm now busy on writing a paper to Haskell Symposium. The deadline is today. So, I will have time after that.

**Comment by greydot** [comment]
>I would like to maintain backward compatibility while making the library bytestring friendly. So, let's discuss requirements first?

Sure. I need functions that work with IPv6 addresses in the same manner {from,to}IPv4 do. I guess that since {to,from}IPv6 are used only in read/show instances implementation, it's ok to change the behaviour of those functions. Frankly, I don't know where else functions taking/producing a list of two-byte values may come handy in case of IPv6.

**Comment by kazu-yamamoto** [comment]
Two-byte style was chosen because the representation of IPv6 address is two-byte style (i.e. separated by ':'). To maintain backward compatibility, the behaviors of {from,to}IPv6 should not change. What about defining new functions, for instance, `fromIPv6'` and `toIPv6'`? If you don't like this approach, please let me know reasons.

**Comment by greydot** [comment]
It's ok, I don't really care about the function names.

**Comment by kazu-yamamoto** [comment]
So, would you modify your patch to change function names? And would you give me a pull request to the dns library if you wish to use the new functions?

**Comment by greydot** [comment]
Done. DNS code will follow later, as its not finished yet.

**Comment by greydot** [comment]
P.S. Sorry for the mixup with tests/exports.

**Comment by kazu-yamamoto** [comment]
A new version has been released. Thank you for your contribution!

**Pull request merged**
