### PR TITLE
Added unmakeAddrRange function.

### PR DESCRIPTION
**Pull request by ondrap**

### CODE REVIEW

**Comment by kazu-yamamoto** [comment]
I feel that `unmake` is strange. What about `addrRangePair`?

Also, you need to fix tests according to Travis. It's easy. Just remove spaces.

**Comment by ondrap** [comment]
I have changed it the way you suggested, is this OK?

**Comment by kazu-yamamoto** [comment]
Looks good. Merged. Thank you for your contribution!

**Comment by kazu-yamamoto** [comment]
Version 1.4.0 has been released.

**Pull request merged**
