### PR TITLE
Introduce lookupWithKey

### PR DESCRIPTION
**Pull request by heroin-moose**
This function is similar to lookup but returns both key and value.

### CODE REVIEW

**Comment by heroin-moose** [comment]
y

**Comment by kazu-yamamoto** [comment]
I pushed a commit to fix Travis CI. You should rebase your topic branch onto `master` and do `push -f`.

**Comment by heroin-moose** [comment]
I don't have a strong preference about the function name. Do you have a more suitable name on your mind?

**Comment by kazu-yamamoto** [comment]
Does `lookupForKey` make sense?

**Comment by heroin-moose** [comment]
Hmm... it's lookForKey then. You cannot really lookup for something. I think that lookupNode or lookupKeyValue is more suitable though.

**Comment by kazu-yamamoto** [comment]
OK. `lookupKeyValue` makes sense to me. Please go ahead!

**Comment by heroin-moose** [comment]
Rebased, pushed.

**Comment by kazu-yamamoto** [comment]
Merged and a new release has been released.
Thank you for your contribution!

**Pull request merged**
